name: CI Workflow

on:
  push:
    branches: 
      - "development" 
      - "main"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - 
       name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
    -
       name: Login to DockerHub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: run integration testing
      run: |
        cd backend
        go test
    -
      name: run docker compose
      run: |
        docker-compose up --build -d
    -     
     name: cypress-run:
     runs-on: ubuntu-20.04
     steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          wait-on: "http://localhost:50000"
          browser: chrome
          headless: true
        
